
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 24 11:35:28 CDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 14;
  public static final int Then = 7;
  public static final int Parentesis_a = 13;
  public static final int Call = 5;
  public static final int Numero = 30;
  public static final int Begin = 12;
  public static final int Mas = 25;
  public static final int Var = 3;
  public static final int Mayor = 18;
  public static final int ERROR = 31;
  public static final int Identificador = 29;
  public static final int Const = 2;
  public static final int Coma = 20;
  public static final int Procedure = 4;
  public static final int End = 11;
  public static final int Asterisco = 23;
  public static final int EOF = 0;
  public static final int Odd = 10;
  public static final int MenorIgual = 16;
  public static final int If = 6;
  public static final int Diagonal = 24;
  public static final int error = 1;
  public static final int Menos = 26;
  public static final int Punto = 22;
  public static final int Menor = 19;
  public static final int MayorIgual = 15;
  public static final int Do = 9;
  public static final int Asignacion = 28;
  public static final int Igual = 17;
  public static final int While = 8;
  public static final int Diferente = 27;
  public static final int PuntoComa = 21;
}

